### ISSUE TITLE
post 관련 api 수정 및 추가 요청

### ISSUE THREAD

**Issue by JJineu** [Between-Departments/dev-BE#1]
/posts
- response 에 유저 프로필 이미지 추가해주세요

/posts/:post_id
- response 에 유저 프로필 이미지 추가해주세요

해당 주차 recommendCount 높은 순으로, post 5개가 필요합니다. 
- order= recommend&
- 시간 범위를 지정하는 로직이 필요할 것 같습니다.

24시간 내 최신순  15개정도 필요합니다.
- 시간 범위를 지정하는 로직이 필요할 것 같습니다.

"category": "free"일 경우, 태그 정보를 포함해야 합니다.
- 연애, 일상, 같이해요, 맛집... 등의 태그에 따라 postlist 를 반환해야 합니다.

익명게시물의 경우, 익명인지 확인할 수 있는 태그가 필요합니다.

**Comment by L-ilac** [comment]
/posts 와 /posts/:post_id 에 들어갈 작성자 프로필 이미지는 어떤게 들어가야하나요? 원본 or 썸네일?

**Comment by JJineu** [comment]
썸네일이 필요합니다.

**Comment by L-ilac** [comment]
1. /posts -> response 에 유저 프로필 이미지 추가하였습니다.

2. /posts/:post_id ->response 에 유저 프로필 이미지 추가하였습니다.

3. 익명게시물에 익명여부를 확인할 수 있는 anonymous를 boolean 값으로 추가하였습니다.

4. "category": "free"일 경우, 태그 정보를 포함해야 합니다. -> 


미해결

1. 게시글 조회시 추천수 기준으로 정렬적용

2. 게시글 조회시 시간 범위 지정 로직
