### ISSUE TITLE
게시글 및 댓글 신고 논의사항

### ISSUE THREAD

**Issue by jeongmin0709** [Between-Departments/dev-BE#12]
게시글 및 댓글 신고 관련해서 논의사항이 3가지 정도 있습니다.
1. 게시글 및 댓글 블러처리
2. 신고 컨트롤러 분리
3. 신고 누적 저장 

1번의 경우 모든 게시글 및 댓글 요청에서 report 테이블과 join을 통해 해당 글이 블러처리가 필요한지 아닌지에대한 값을 가져오는게 꼭필요한가에 대한 의문이 들었습니다. 데이터 삭제가 오히려 나은 방법이 아닐까요. 또 블러처리가 필요한 글일 경우 데이터는 그대로주고 필드하나로 블러처리를 나타낼지 아니면 아예 데이터를 주지않고 예외를 터트릴지에 대한 고민입니다.

2번의 경우 report자체로도 create read delete를 모두 필요로 하기 떄문에 controller를 따로 분리하는게 좋다고 생각해서 의견을 듣고싶습니다. 그리고 만약 분리한다면 replyReport와 postReport 까지 분리가 필요한가에대해서도 의견을 듣고 싶습니다.

3번의 경우 신고누적을 어느테이블에 저장할지에 대한 내용입니다.  예을들어 post에 누적카운트를 저장할지 혹은 postReport에 boolean type 으로 누적여부로 저장할지에 대해 의견을 듣고 싶습니다.

+댓글, 게시글 이후 각자 어느 기능을 개발할지에 대한 논의도 필요할것 같습니다.

**Comment by L-ilac** [comment]
댓글, 게시물 이후의 기능 개발은 크게 알림 or 채팅인거같은데, 둘다 웹소켓을 이용해서 실시간으로 데이터를 서버에서 사용자에게 푸시해주는 형식이라면, 저는 둘중에 아무거나 맡아도 상관없을 것 같아요.

**Comment by jeongmin0709** [comment]
1, 삭제쪽으로 정하면 될거같습니다.

2. controller는 신고로 통일하고 service에서 나눠서 개발하면 될거같습니다.

3. 다시 생각해보니 작성글에대한 신고 누적이 의미가 있는지 모르겠네요. 유효한 신고가 1건이라도 있으면 해당 게시글을 삭제하거나 블러처리를 해야하니까요.  오히려 작성자에 대한 누적 기능이 필요하지 않을까요. 신고당해서 블러처리를 당한 작성글을 많이썻다면 악성 유저라는 뜻이니까요.  정지할때나 강제 탈퇴시킬떄 유효한 정보라고 생각합니다.

4. 그러면 제가 채팅 기능을 개발하고 세승님이 알림쪽을 맡아주시면 감사하겠습니다.

**Comment by L-ilac** [comment]
1. 삭제쪽으로 가는건 프론트, 디자인 분들하고 협의가 된건가요?

2. 답변을 제가 제대로 이해를 못했는데 구체적으로 설명해주실수 있을까요?

3. 유효한 신고가 3건이 누적되어야만 삭제 or 블러처리 해야하는거 아니었나요? 회의에서 유효한 신고가 1건이라도 있으면 삭제 or 블러처리하는걸로 결정되지않았던걸로 기억합니다. 확인이 필요하네요. 
+ 작성자에 대한 신고당한 횟수는 ADMIN의 계정관리 페이지에서 유용할 거 같긴한데, 다른 팀원분들이랑도 얘기를 해봐야할 것 같습니다.

4. 확인했습니다.

**Comment by L-ilac** [comment]
1. 특정 게시물 또는 댓글이 1회라도 ADMIN에 의해 올바른 신고로 처리되면, 해당 게시물 또는 댓글 삭제 + 사용자에 대한 누적신고카운트 +1
2. ReportController에서 PostReportService, ReplyReportService 두개 주입받아서 사용
3. 1번에 포함되어있음

**Comment by jeongmin0709** [comment]
3번의 경우 누적카운트를 member쪽에 다는게 맞는거같네요
