### ISSUE TITLE
Fetch Join 과 @EntityGraph를 사용 시 SQL 쿼리 차이점

### ISSUE THREAD

**Issue by L-ilac** [Between-Departments/dev-BE#13]
@EntityGraph로 @OneToMany가 걸려있는 엔티티를 같이 갖고올 때, Left Join으로 SQL 쿼리가 나갑니다.

-Reference
https://velog.io/@xogml951/EntityGraph%EC%99%80-fetch-join-%EC%B0%A8%EC%9D%B4

**Comment by jeongmin0709** [comment]
넵 좋은 정보 감사합니다~
