### ISSUE TITLE
게시글 작성 관련 API 형식 수정 요청입니다.

### ISSUE THREAD

**Issue by H0onnn** [Between-Departments/dev-BE#16]
안녕하세요 ! 개발 중 API req 형식에 대한 수정사항이 있어 이슈 남깁니다.

1. 게시글 작성 (/api/posts)

현재 req body 형식이 아래와 같은데,

{
  "title": "string",
  "content": "string",
  "major": "string",
  "category": "NEED_HELP",
  "anonymous": true
}

게시글 작성에 이미지도 들어가기 때문에 images arr도 받을 수 있도록 추가 요청드립니다 !

2. category 의 경우 '도움이 필요해요', '자유게시판' 을 분류하는 카테고리 항목으로 보이는데, 자유게시판에 글을 작성할 때 전체, 일상, 연애 등 상세 카테고리에 대한 처리는 어떻게 해야할지 문의드립니다 :)

**Comment by L-ilac** [comment]
1. 반영했습니다.
2. 카테고리 분류를 새롭게 변경했습니다. 
- boardType으로 '자유게시판' or '도움이 필요해요' 로 분류
- '자유게시판'일 경우 tag로 상세 카테고리 설정
- '도움이 필요해요'일 경우 major로 계열 설정

**Comment by L-ilac** [comment]
위의 예시를 참고하여 말씀드리면, 사실 둘 중 어떤 방식으로 보내던 백엔드 서버에서는 tag 값에는 null 값이 들어갑니다.

하지만, boardType에 따라 전송되는 데이터가 다르다는 것을 확실히 하기 위해서는 2번 예시로 보내주는게 좀 더 명확할 것 같긴 하네요.
