### ISSUE TITLE
신고 기능 관련 질문

### ISSUE THREAD

**Issue by L-ilac** [Between-Departments/dev-BE#4]
고민해봐야할 점

1. 와이어프레임 워크 상의 확인 완료 버튼은 무엇은 위한 기능인가?
2. 익명으로 작성한 글은 ADMIN에게도 익명으로 보여야하는가?
3.  \+ α

**Comment by H0onnn** [comment]
디자이너분들께 문의 후 받은 답변 공유드립니다 !

저희가 기획했던 신고 및 정지 기능은 "같은 사용자가 총 3번 신고 당했을 경우 계정 정지 처리가 되도록 하자." 였습니다.

1. 확인완료 버튼은 어드민이 신고된 내역을 확인하고, 정말 신고당할 게시글이나 댓글일 경우 완료 처리를 하는 버튼입니다. 삭제하기 버튼의 경우 허위 신고일 때 신고를 삭제 처리 하는 버튼입니다. 확인완료 버튼으로 확인이 총 3회 누적된 계정의 경우 자동으로 계정 정지 처리를 당해야합니다.

2. 익명으로 작성한 게시글은 어드민 페이지에서는 본래의 닉네임이 보여야 합니다. 어떤 사용자가 신고를 당하고, 신고 했는지 한 눈에 확인하기 위함입니다 !

**Comment by L-ilac** [comment]
1번 답변에 대한 추가 질문입니다!

'같은 사용자가 총 3번 신고 당했을 경우' 라는건, 단일 게시물 신고 횟수에 한해서 인가요? 아니면 총 신고 수에 한해서 인가요?
예를 들어서 사용자 A가 작성한 게시물 1, 게시물 2, 게시물 3이 있을 때, 게시물 1에 신고가 3번 누적되어야 계정 정지 처리인지, 3개의 게시물에 대한 총 신고 누적 횟수가 3번일 때 정지인 건지 궁금합니다.

+ 계정 정지 처리가 되어야하는 신고 횟수로 3번이 적절한 것인지에 대한 논의가 필요해 보이고, 계정 정지 처리 대신 특정 기능 사용에 대한 제한과 같은 징계 형식의 페널티 적용에 대해서 어떻게 생각하시는지도 궁금하네요.

**Comment by L-ilac** [comment]
확인했습니다!

**Comment by L-ilac** [comment]
신고 관련 질문 하나 더 드립니다!

특정 게시물에 대한 신고의 경우, 사용자별 1개씩으로 제한하나요?
예를 들어, 사용자 A가 게시물 1에 대한 신고를 하는데, 사유를 전부 다르게해서 신고하는게 가능한지 궁금하네요.
그리고 만약에 특정 게시물에 대한 1명의 사용자의 중복 신고(모두 다른 사유)를 허용한다면, 해당 신고는 서로 다른 신고로 간주해서 카운트 해야할까요?

**Comment by H0onnn** [comment]
네 하나의 게시글에 대해서 같은 사용자가 중복으로 신고하는건 금지됩니다 ! 한 사용자는 하나의 게시글에 한 번의 신고만 가능합니다

**Comment by L-ilac** [comment]
확인했습니다!
