### ISSUE TITLE
새로운 데이터를 생성하는 API와 조회 API의 분리 여부

### ISSUE THREAD

**Issue by L-ilac** [Between-Departments/dev-BE#8]
현재 Postman API 스펙에는 새로운 데이터를 생성하는 API(게시물 생성, 댓글 생성 등)가 POST 요청에 대한 응답으로 생성된 데이터를 반환하고 있습니다. 고민해볼거리가 생겨서 질문 남깁니다.

1. 현행대로 간다 -> 데이터 생성용 API 요청에 대한 응답으로 생성된 데이터를 넣는다.
2. 생성용 API와 조회용 API를 분리한다 -> 데이터 생성을 위한 API에는 CREATED(201) 응답 또는 생성된 데이터의 id값만 반환하고, 생성된 데이터의 세부적인 내용은 조회용 API를 통해 추가 요청하도록 한다.

\+ 위의 질문은 수정용 API에도 동일하게 적용가능합니다.

**Comment by jeongmin0709** [comment]
데이터 생성시에는 거의 대부분 생성된 데이터를 필요로 하기 때문에 응답으로 생성된 데이터를 넣는게 좋다고 생각합니다. api 요청을 줄이는게 서버에 부담도 덜될것 같습니다.
수정용 api는 3가지 정도 선택지가 있는것같습니다.
1. 데이터를 응답하지 않는다.
2. 변경된 데이터만 응답한다.
3. 모든 데이터를 응답한다.
수정용 api에는 이미 해당 데이터의 id나 변경전 데이터를 가지고 있기 때문에 구현이 가장쉬운 1번이 좋지않나 싶습니다.

**Comment by L-ilac** [comment]
생성용 API 에는 생성된 데이터를 응답하고, 수정용 API에는 데이터 없이 OK(HTTP Status 200)로 응답하는 걸로 하겠습니다.
